In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("test2.csv")

In [3]:
df.head(5)

,Unnamed: 0,0_x,0_y,1_x,1_y,2_x,2_y,3_x,3_y,4_x,...,66_x,66_y,67_x,67_y,Gaze,Blink,Blush,Brows,QuestionType,QuestionNumber
0,0,47,94,48,116,51,137,54,158,62,...,131,169,124,169,center,no blink,0.000000,normal,truth,1
1,1,43,90,44,113,47,136,51,159,58,...,130,175,122,174,right,blink,-1.581693,normal,truth,1
2,2,46,94,47,116,50,137,53,159,61,...,129,176,122,176,center,no blink,-0.884483,normal,truth,1
3,3,47,96,48,117,50,139,54,160,62,...,129,176,121,175,center,no blink,-0.146759,normal,truth,1
4,4,47,97,48,119,51,140,54,161,62,...,128,176,121,175,center,no blink,-0.671026,normal,truth,1

In [4]:
df = pd.concat([df,pd.get_dummies(df['Gaze'], prefix='Gaze')],axis=1).drop(['Gaze'],axis=1)
df = pd.concat([df,pd.get_dummies(df['Blink'], prefix='Blink')],axis=1).drop(['Blink'],axis=1)
df = pd.concat([df,pd.get_dummies(df['Brows'], prefix='Brows')],axis=1).drop(['Brows'],axis=1)
df = pd.concat([df,pd.get_dummies(df['QuestionType'], prefix='QuestionType')],axis=1).drop(['QuestionType'],axis=1)

In [5]:
# Create x, where x the 'scores' column's values as floats
df[['Blush']] = df[['Blush']].values.astype(float)

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
x_scaled = min_max_scaler.fit_transform(df[['Blush']])

# Run the normalizer on the dataframe
df[['Blush']] = pd.DataFrame(x_scaled)

In [6]:
df

,Unnamed: 0,0_x,0_y,1_x,1_y,2_x,2_y,3_x,3_y,4_x,...,Gaze_center,Gaze_left,Gaze_right,Blink_blink,Blink_no blink,Brows_high,Brows_low,Brows_normal,QuestionType_lie,QuestionType_truth
0,0,47,94,48,116,51,137,54,158,62,...,1,0,0,0,1,0,0,1,0,1
1,1,43,90,44,113,47,136,51,159,58,...,0,0,1,1,0,0,0,1,0,1
2,2,46,94,47,116,50,137,53,159,61,...,1,0,0,0,1,0,0,1,0,1
3,3,47,96,48,117,50,139,54,160,62,...,1,0,0,0,1,0,0,1,0,1
4,4,47,97,48,119,51,140,54,161,62,...,1,0,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45507,45507,44,85,45,108,49,130,54,152,61,...,0,1,0,0,1,0,0,1,1,0
45508,45508,46,87,47,110,51,132,56,153,64,...,1,0,0,0,1,0,0,1,1,0
45509,45509,46,88,47,110,51,132,56,153,65,...,1,0,0,0,1,0,0,1,1,0
45510,45510,46,88,47,110,51,132,57,154,66,...,0,1,0,0,1,0,0,1,1,0
45511,45511,47,88,48,110,51,132,57,154,66,...,0,1,0,0,1,0,0,1,1,0

In [7]:
y = df['QuestionType_truth']

In [8]:
X = df[['20_y', '21_y', '22_y','23_y', '24_y', '25_y', '26_y','Blush', 'Gaze_center', 'Gaze_left', 'Gaze_right', 'Blink_blink','Blink_no blink', 'Brows_high', 'Brows_low', 'Brows_normal' ]]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=109)

In [9]:

clf=RandomForestClassifier(n_estimators=10)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [10]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8461989160685514

In [11]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='macro')

0.8457409040695364

In [12]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[6149,  849],
       [1251, 5405]], dtype=int64)

In [13]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      6998
           1       0.86      0.81      0.84      6656

    accuracy                           0.85     13654
   macro avg       0.85      0.85      0.85     13654
weighted avg       0.85      0.85      0.85     13654

In [14]:
import numpy as np
from sklearn.model_selection import cross_val_score


cv = np.mean(cross_val_score(clf, X_train, y_train, cv=10))
print ("Accuracy using RF with 10 cross validation : {}%".format(round(cv*100,2)))
y_predict_test = clf.predict(X_test)

#F1_score

score_test = metrics.f1_score(y_test, y_predict_test, 
                              pos_label=list(set(y_test)), average = None)


score_test

Accuracy using RF with 10 cross validation : 84.72%

C:\Users\laure\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to [0, 1]) is ignored when average != 'binary' (got None). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)

array([0.85414641, 0.8373354 ])